In [2]:
import numpy as np
import pandas as pd

In [3]:
data = pd.read_excel("DA -Task 2..xlsx", sheet_name=0)

In [7]:
data.head(5)

,VIN,TRANSACTION_ID,CORRECTION_VERBATIM,CUSTOMER_VERBATIM,REPAIR_DATE,CAUSAL_PART_NM,GLOBAL_LABOR_CODE_DESCRIPTION,PLATFORM,BODY_STYLE,VPPC,...,TRANSMISSION_TRACE_NBR,SRC_TXN_ID,SRC_VER_NBR,TRANSACTION_CNTR,MEDIA_FLAG,VIN_MODL_DESGTR,LINE_SERIES,LAST_KNOWN_DELVRY_TYPE_CD,NON_CAUSAL_PART_QTY,SALES_REGION_CODE
0,3HCFDDE89SH220903,13021,REPLACED STEERING WHEEL NOW OKAY,STEERING WHEEL COMING APART,2024-01-02,WHEEL ASM-STRG *JET BLACK,Steering Wheel Replacement,Full-Size Trucks,Crew Cab,T1CCF,...,S2210121CNJX0941,2808908219,6,1,N,CF10543,1500,21.0,0,1
1,1HRFFEE8XSZ230636,13028,CHECKED - FOUND DTC'S U0229 - U1530 SET IN BCM...,CUSTOMER STATES HEATED STEERING WHEEL INOP,2024-01-03,MODULE ASM-STRG WHL HT CONT,Heated Steering Wheel Module Replacement,Full-Size Trucks,Crew Cab,T1CGF,...,R2210881CNJX0287,2808841910,6,1,Y,TF10543,1500,10.0,0,1
2,1HYKSMRK6SZ000990,13035,APPROVED 4.9(OLH) FOR ADDED DIAGNOSTICS WITH T...,OWNER REPORTS: THE SUPER CRUISE BAR ON THE STE...,2024-01-04,WHEEL ASM-STRG *BACKEN BLACKK,Steering Wheel Replacement,BEV,4 Door Utility,L233-LSOP,...,NaN,2809979441,4,1,Y,6MB26,Lux-1,10.0,0,1
3,3HCFDFEL3SH241701,13021,STEERING WHEEL REPLACEMENT,CUSTOMER STATES THE LETTERING AND FINISH ON TH...,2024-01-04,WHEEL ASM-STRG *JET BLACK,Steering Wheel Replacement,Full-Size Trucks,Crew Cab,T1CCF,...,S1210822CKJX0291,2808892288,6,1,Y,CF10543,1500,10.0,0,1
4,1HRFFHEL1RZ181474,13021,REPLACED STEERING MESSAGE NO LONGER DISPLAYED,C/S: CUSTOMER STATES THE SERVICE DRIVER ASSIST...,2024-01-05,WHEEL ASM-STRG *JET BLACK,Steering Wheel Replacement,Full-Size Trucks,Crew Cab,T1CGF,...,R2212982CKJX0282,2808901882,8,1,N,TF10543,1500,10.0,0,1

In [7]:
data.shape # Display the shape of the DataFrame to understand its dimensions

(100, 52)

In [8]:
data.describe() # Display summary statistics of the DataFrame to understand the data distribution

,TRANSACTION_ID,REPAIR_DATE,DEALER_REGION,REPAIR_AGE,KM,COMPLAINT_CD_CSI,ORD_SELLING_SRC_CD,GLOBAL_LABOR_CODE,CAMPAIGN_NBR,REPORTING_COST,TOTALCOST,LBRCOST,TRANSMISSION_SOURCE_PLANT,SRC_TXN_ID,SRC_VER_NBR,TRANSACTION_CNTR,LAST_KNOWN_DELVRY_TYPE_CD,NON_CAUSAL_PART_QTY,SALES_REGION_CODE
count,100.000000,100,100.00000,100.000000,100.000000,100.0,100.000000,100.000000,0.0,100.000000,94.000000,100.000000,8.800000e+01,1.000000e+02,100.000000,100.0,98.000000,100.000000,100.00000
mean,13036.900000,2024-01-22 07:26:24,1.09000,14.940000,24914.230000,0.0,24.590000,251.900000,NaN,531.193200,561.162128,106.344900,1.676383e+08,2.815767e+09,5.720000,1.0,14.132653,0.070000,1.09000
min,13021.000000,2024-01-02 00:00:00,1.00000,0.000000,3.000000,0.0,11.000000,20.000000,NaN,27.690000,27.690000,20.000000,2.878270e+05,2.808842e+09,2.000000,1.0,10.000000,0.000000,1.00000
25%,13027.750000,2024-01-12 00:00:00,1.00000,5.000000,8883.250000,0.0,13.000000,130.000000,NaN,305.432500,320.105000,61.855000,2.878270e+05,2.809436e+09,4.000000,1.0,10.000000,0.000000,1.00000
50%,13036.000000,2024-01-24 12:00:00,1.00000,12.000000,21962.000000,0.0,13.000000,130.000000,NaN,433.970000,457.225000,78.560000,8.042172e+06,2.820097e+09,4.000000,1.0,10.000000,0.000000,1.00000
75%,13041.250000,2024-02-01 00:00:00,1.00000,21.000000,35493.250000,0.0,48.000000,130.000000,NaN,554.062500,606.905000,108.055000,1.774929e+07,2.820880e+09,6.000000,1.0,16.000000,0.000000,1.00000
max,13081.000000,2024-02-07 00:00:00,4.00000,50.000000,107905.000000,0.0,72.000000,2400.000000,NaN,2457.450000,3205.450000,1012.670000,8.282984e+08,2.823000e+09,26.000000,1.0,37.000000,1.000000,4.00000
std,12.028166,NaN,0.51434,12.367945,20747.078206,0.0,17.822976,546.451722,NaN,411.161608,452.796836,113.223074,3.237538e+08,5.790727e+06,4.040402,0.0,6.694570,0.256432,0.51434

In [ ]:




# dataset Overview
print("Shape (rows, columns):", data.shape)
print("\nColumn Names:\n", data.columns.tolist())
print("\nData Types:\n", data.dtypes)

print("\nMissing Values per Column:\n", data.isnull().sum())
print("\nBasic Statistics:\n", data.describe(include='all'))  # includes both numeric & categorical


# Check how many duplicate rows exist
print("Number of duplicate rows:", data.duplicated().sum())

#  View duplicate rows (if any)
print("\nDuplicate rows:")
print(data[data.duplicated()])

Shape (rows, columns): (100, 52)

Column Names:
 ['VIN', 'TRANSACTION_ID', 'CORRECTION_VERBATIM', 'CUSTOMER_VERBATIM', 'REPAIR_DATE', 'CAUSAL_PART_NM', 'GLOBAL_LABOR_CODE_DESCRIPTION', 'PLATFORM', 'BODY_STYLE', 'VPPC', 'PLANT', 'BUILD_COUNTRY', 'LAST_KNOWN_DLR_NAME', 'LAST_KNOWN_DLR_CITY', 'REPAIRING_DEALER_CODE', 'DEALER_NAME', 'REPAIR_DLR_CITY', 'STATE', 'DEALER_REGION', 'REPAIR_DLR_POSTAL_CD', 'REPAIR_AGE', 'KM', 'COMPLAINT_CD_CSI', 'COMPLAINT_CD', 'VEH_TEST_GRP', 'COUNTRY_SALE_ISO', 'ORD_SELLING_SRC_CD', 'OPTN_FAMLY_CERTIFICATION', 'OPTF_FAMLY_EMISSIOF_SYSTEM', 'GLOBAL_LABOR_CODE', 'TRANSACTION_CATEGORY', 'CAMPAIGN_NBR', 'REPORTING_COST', 'TOTALCOST', 'LBRCOST', 'ENGINE', 'ENGINE_DESC', 'TRANSMISSION', 'TRANSMISSION_DESC', 'ENGINE_SOURCE_PLANT', 'ENGINE_TRACE_NBR', 'TRANSMISSION_SOURCE_PLANT', 'TRANSMISSION_TRACE_NBR', 'SRC_TXN_ID', 'SRC_VER_NBR', 'TRANSACTION_CNTR', 'MEDIA_FLAG', 'VIN_MODL_DESGTR', 'LINE_SERIES', 'LAST_KNOWN_DELVRY_TYPE_CD', 'NON_CAUSAL_PART_QTY', 'SALES_REGION_CODE']

Data Types:
 VIN                                      object
TRANSACTION_ID                            int64
CORRECTION_VERBATIM                      object
CUSTOMER_VERBATIM                        object
REPAIR_DATE                      datetime64[ns]
CAUSAL_PART_NM                           object
GLOBAL_LABOR_CODE_DESCRIPTION            object
PLATFORM                                 object
BODY_STYLE                               object
VPPC                                     object
PLANT                                    object
BUILD_COUNTRY                            object
LAST_KNOWN_DLR_NAME                      object
LAST_KNOWN_DLR_CITY                      object
REPAIRING_DEALER_CODE                    object
DEALER_NAME                              object
REPAIR_DLR_CITY                          object
STATE                                    object
DEALER_REGION                             int64
REPAIR_DLR_POSTAL_CD                     object
REPAIR_AGE                                int64
KM                                        int64
COMPLAINT_CD_CSI                          int64
COMPLAINT_CD                             object
VEH_TEST_GRP                             object
COUNTRY_SALE_ISO                         object
ORD_SELLING_SRC_CD                        int64
OPTN_FAMLY_CERTIFICATION                 object
OPTF_FAMLY_EMISSIOF_SYSTEM               object
GLOBAL_LABOR_CODE                         int64
TRANSACTION_CATEGORY                     object
CAMPAIGN_NBR                            float64
REPORTING_COST                          float64
TOTALCOST                               float64
LBRCOST                                 float64
ENGINE                                   object
ENGINE_DESC                              object
TRANSMISSION                             object
TRANSMISSION_DESC                        object
ENGINE_SOURCE_PLANT                      object
ENGINE_TRACE_NBR                         object
TRANSMISSION_SOURCE_PLANT               float64
TRANSMISSION_TRACE_NBR                   object
SRC_TXN_ID                                int64
SRC_VER_NBR                               int64
TRANSACTION_CNTR                          int64
MEDIA_FLAG                               object
VIN_MODL_DESGTR                          object
LINE_SERIES                              object
LAST_KNOWN_DELVRY_TYPE_CD               float64
NON_CAUSAL_PART_QTY                       int64
SALES_REGION_CODE                         int64
dtype: object

Missing Values per Column:
 VIN                                0
TRANSACTION_ID                     0
CORRECTION_VERBATIM                0
CUSTOMER_VERBATIM                  0
REPAIR_DATE                        0
CAUSAL_PART_NM                     5
GLOBAL_LABOR_CODE_DESCRIPTION      0
PLATFORM                           0
BODY_STYLE                         0
VPPC                               0
PLANT                              1
BUILD_COUNTRY                      0
LAST_KNOWN_DLR_NAME                0
LAST_KNOWN_DLR_CITY                0
REPAIRING_DEALER_CODE              0
DEALER_NAME                        0
REPAIR_DLR_CITY                    0
STATE                              2
DEALER_REGION                      0
REPAIR_DLR_POSTAL_CD               2
REPAIR_AGE                         0
KM                                 0
COMPLAINT_CD_CSI                   0
COMPLAINT_CD                       0
VEH_TEST_GRP                       2
COUNTRY_SALE_ISO                   0
ORD_SELLING_SRC_CD                 0
OPTN_FAMLY_CERTIFICATION          10
OPTF_FAMLY_EMISSIOF_SYSTEM         5
GLOBAL_LABOR_CODE                  0
TRANSACTION_CATEGORY               0
CAMPAIGN_NBR                     100
REPORTING_COST                     0
TOTALCOST                          6
LBRCOST                            0
ENGINE                             0
ENGINE_DESC                        0
TRANSMISSION                       0
TRANSMISSION_DESC                  0
ENGINE_SOURCE_PLANT               12
ENGINE_TRACE_NBR                  12
TRANSMISSION_SOURCE_PLANT         12
TRANSMISSION_TRACE_NBR            12
SRC_TXN_ID                         0
SRC_VER_NBR                        0
TRANSACTION_CNTR                   0
MEDIA_FLAG                         0
VIN_MODL_DESGTR                    0
LINE_SERIES                        1
LAST_KNOWN_DELVRY_TYPE_CD          2
NON_CAUSAL_PART_QTY                0
SALES_REGION_CODE                  0
dtype: int64

Basic Statistics:
                       VIN  TRANSACTION_ID      CORRECTION_VERBATIM  \
count                 100      100.000000                      100
unique                 98             NaN                       93
top     3HRS9EED0LH255650             NaN  Replaced steering wheel
freq                    2             NaN                        3
mean                  NaN    13036.900000                      NaN
min                   NaN    13021.000000                      NaN
25%                   NaN    13027.750000                      NaN
50%                   NaN    13036.000000                      NaN
75%                   NaN    13041.250000                      NaN
max                   NaN    13081.000000                      NaN
std                   NaN       12.028166                      NaN

                  CUSTOMER_VERBATIM          REPAIR_DATE  \
count                           100                  100
unique                          100                  NaN
top     STEERING WHEEL COMING APART                  NaN
freq                              1                  NaN
mean                            NaN  2024-01-22 07:26:24
min                             NaN  2024-01-02 00:00:00
25%                             NaN  2024-01-12 00:00:00
50%                             NaN  2024-01-24 12:00:00
75%                             NaN  2024-02-01 00:00:00
max                             NaN  2024-02-07 00:00:00
std                             NaN                  NaN

                   CAUSAL_PART_NM GLOBAL_LABOR_CODE_DESCRIPTION  \
count                          95                           100
unique                         18                             4
top     WHEEL ASM-STRG *JET BLACK    Steering Wheel Replacement
freq                           45                            78
mean                          NaN                           NaN
min                           NaN                           NaN
25%                           NaN                           NaN
50%                           NaN                           NaN
75%                           NaN                           NaN
max                           NaN                           NaN
std                           NaN                           NaN

                PLATFORM BODY_STYLE   VPPC  ... TRANSMISSION_TRACE_NBR  \
count                100        100    100  ...                     88
unique                11          6     26  ...                     88
top     Full-Size Trucks   Crew Cab  T1CCF  ...       S2210121CNJX0941
freq                  52         50     20  ...                      1
mean                 NaN        NaN    NaN  ...                    NaN
min                  NaN        NaN    NaN  ...                    NaN
25%                  NaN        NaN    NaN  ...                    NaN
50%                  NaN        NaN    NaN  ...                    NaN
75%                  NaN        NaN    NaN  ...                    NaN
max                  NaN        NaN    NaN  ...                    NaN
std                  NaN        NaN    NaN  ...                    NaN

          SRC_TXN_ID SRC_VER_NBR TRANSACTION_CNTR MEDIA_FLAG VIN_MODL_DESGTR  \
count   1.000000e+02  100.000000            100.0        100             100
unique           NaN         NaN              NaN          2              41
top              NaN         NaN              NaN          N         CF10543
freq             NaN         NaN              NaN         62              15
mean    2.815767e+09    5.720000              1.0        NaN             NaN
min     2.808842e+09    2.000000              1.0        NaN             NaN
25%     2.809436e+09    4.000000              1.0        NaN             NaN
50%     2.820097e+09    4.000000              1.0        NaN             NaN
75%     2.820880e+09    6.000000              1.0        NaN             NaN
max     2.823000e+09   26.000000              1.0        NaN             NaN
std     5.790727e+06    4.040402              0.0        NaN             NaN

       LINE_SERIES LAST_KNOWN_DELVRY_TYPE_CD  NON_CAUSAL_PART_QTY  \
count         99.0                 98.000000           100.000000
unique        22.0                       NaN                  NaN
top         1500.0                       NaN                  NaN
freq          52.0                       NaN                  NaN
mean           NaN                 14.132653             0.070000
min            NaN                 10.000000             0.000000
25%            NaN                 10.000000             0.000000
50%            NaN                 10.000000             0.000000
75%            NaN                 16.000000             0.000000
max            NaN                 37.000000             1.000000
std            NaN                  6.694570             0.256432

        SALES_REGION_CODE
count           100.00000
unique                NaN
top                   NaN
freq                  NaN
mean              1.09000
min               1.00000
25%               1.00000
50%               1.00000
75%               1.00000
max               4.00000
std               0.51434

[11 rows x 52 columns]
Number of duplicate rows: 0

Duplicate rows:
Empty DataFrame
Columns: [VIN, TRANSACTION_ID, CORRECTION_VERBATIM, CUSTOMER_VERBATIM, REPAIR_DATE, CAUSAL_PART_NM, GLOBAL_LABOR_CODE_DESCRIPTION, PLATFORM, BODY_STYLE, VPPC, PLANT, BUILD_COUNTRY, LAST_KNOWN_DLR_NAME, LAST_KNOWN_DLR_CITY, REPAIRING_DEALER_CODE, DEALER_NAME, REPAIR_DLR_CITY, STATE, DEALER_REGION, REPAIR_DLR_POSTAL_CD, REPAIR_AGE, KM, COMPLAINT_CD_CSI, COMPLAINT_CD, VEH_TEST_GRP, COUNTRY_SALE_ISO, ORD_SELLING_SRC_CD, OPTN_FAMLY_CERTIFICATION, OPTF_FAMLY_EMISSIOF_SYSTEM, GLOBAL_LABOR_CODE, TRANSACTION_CATEGORY, CAMPAIGN_NBR, REPORTING_COST, TOTALCOST, LBRCOST, ENGINE, ENGINE_DESC, TRANSMISSION, TRANSMISSION_DESC, ENGINE_SOURCE_PLANT, ENGINE_TRACE_NBR, TRANSMISSION_SOURCE_PLANT, TRANSMISSION_TRACE_NBR, SRC_TXN_ID, SRC_VER_NBR, TRANSACTION_CNTR, MEDIA_FLAG, VIN_MODL_DESGTR, LINE_SERIES, LAST_KNOWN_DELVRY_TYPE_CD, NON_CAUSAL_PART_QTY, SALES_REGION_CODE]
Index: []

[0 rows x 52 columns]

In [14]:


# ðŸ”¹ Separate columns by type
cat_cols = data.select_dtypes(include=['object', 'category']).columns
num_cols = data.select_dtypes(include=['number']).columns
date_cols = data.select_dtypes(include=['datetime64[ns]']).columns

print("Categorical Columns:", cat_cols.tolist())
print("Numerical Columns:", num_cols.tolist())
print("Datetime Columns:", date_cols.tolist())

# ðŸ”¹ Insights for categorical columns
print("\n=== Categorical Column Insights ===")
for col in cat_cols:
    missing_pct = data[col].isnull().mean() * 100
    print(f"\nColumn: {col}")
    print("Missing %:", round(missing_pct, 2))
    print("Unique values:", data[col].nunique())
    if data[col].nunique() > 0:
        print("Most frequent value:", data[col].mode()[0])
    print("Top 5 value counts:\n", data[col].value_counts().head())

# ðŸ”¹ Insights for numerical columns
print("\n=== Numerical Column Insights ===")
for col in num_cols:
    missing_pct = data[col].isnull().mean() * 100
    print(f"\nColumn: {col}")
    print("Missing %:", round(missing_pct, 2))
    print(data[col].describe())

# ðŸ”¹ Insights for datetime columns
print("\n=== Datetime Column Insights ===")
for col in date_cols:
    missing_pct = data[col].isnull().mean() * 100
    print(f"\nColumn: {col}")
    print("Missing %:", round(missing_pct, 2))
    if data[col].notnull().sum() > 0:
        print("Min date:", data[col].min())
        print("Max date:", data[col].max())
        print("Unique dates:", data[col].nunique())

Categorical Columns: ['VIN', 'CORRECTION_VERBATIM', 'CUSTOMER_VERBATIM', 'CAUSAL_PART_NM', 'GLOBAL_LABOR_CODE_DESCRIPTION', 'PLATFORM', 'BODY_STYLE', 'VPPC', 'PLANT', 'BUILD_COUNTRY', 'LAST_KNOWN_DLR_NAME', 'LAST_KNOWN_DLR_CITY', 'REPAIRING_DEALER_CODE', 'DEALER_NAME', 'REPAIR_DLR_CITY', 'STATE', 'REPAIR_DLR_POSTAL_CD', 'COMPLAINT_CD', 'VEH_TEST_GRP', 'COUNTRY_SALE_ISO', 'OPTN_FAMLY_CERTIFICATION', 'OPTF_FAMLY_EMISSIOF_SYSTEM', 'TRANSACTION_CATEGORY', 'ENGINE', 'ENGINE_DESC', 'TRANSMISSION', 'TRANSMISSION_DESC', 'ENGINE_SOURCE_PLANT', 'ENGINE_TRACE_NBR', 'TRANSMISSION_TRACE_NBR', 'MEDIA_FLAG', 'VIN_MODL_DESGTR', 'LINE_SERIES']
Numerical Columns: ['TRANSACTION_ID', 'DEALER_REGION', 'REPAIR_AGE', 'KM', 'COMPLAINT_CD_CSI', 'ORD_SELLING_SRC_CD', 'GLOBAL_LABOR_CODE', 'CAMPAIGN_NBR', 'REPORTING_COST', 'TOTALCOST', 'LBRCOST', 'TRANSMISSION_SOURCE_PLANT', 'SRC_TXN_ID', 'SRC_VER_NBR', 'TRANSACTION_CNTR', 'LAST_KNOWN_DELVRY_TYPE_CD', 'NON_CAUSAL_PART_QTY', 'SALES_REGION_CODE']
Datetime Columns: ['REPAIR_DATE']

=== Categorical Column Insights ===

Column: VIN
Missing %: 0.0
Unique values: 98
Most frequent value: 1HRFFHEL8RZ133325
Top 5 value counts:
 VIN
3HRS9EED0LH255650    2
1HRFFHEL8RZ133325    2
3HCFDDE89SH220903    1
3HRFFHEL3SH345370    1
3HCFDHEL2SH305075    1
Name: count, dtype: int64

Column: CORRECTION_VERBATIM
Missing %: 0.0
Unique values: 93
Most frequent value: REPLACED STEERING WHEEL
Top 5 value counts:
 CORRECTION_VERBATIM
Replaced steering wheel                                                                 3
REPLACED STEERING WHEEL                                                                 3
Steering Wheel Replacement                                                              3
REPLACED STEERING WHEEL.                                                                2
REPLACED STEERING WHEEL ASSEMBLY UNDER WARRANTY DUE TO MANFACTURER DEFECT. COMPLETE.    1
Name: count, dtype: int64

Column: CUSTOMER_VERBATIM
Missing %: 0.0
Unique values: 100
Most frequent value: #UPDATE#CUSTOMER STATES VEHICLE'S STEERING WHEEL WAS SMOKING OUT OF THERIGHT SIDE OF WHEEL AND AFTER STEERING WHEEL HEATER WAS SHUTOFF SMOKING STOPPED. PLEASE CHECK AND ADVISE.C/S: SOP INSTALL PARTS HERE PER DREW H. - HISTORY RO 431014 - STEERING WHEEL -CUSTOMERTO SEE ROB C.
Top 5 value counts:
 CUSTOMER_VERBATIM
STEERING WHEEL COMING APART                                                                                                                                                                                                                                1
Rear wiper not working cust thawed out veh and jiggled the control arm a couple times then it worked after trying several timescustthinks signal is not getting fromn front to back wiring Cust has a video of the process he performed Diagnose report    1
LEATHER ON STEERING WHEEL COMING LOOSE ON BOTTOM.                                                                                                                                                                                                          1
CUST STATES STEERING WHEEL DOES NOT HEAT UP COMPLETELY ONLY ONE SMALL SPOT SOP IN                                                                                                                                                                          1
CUSTOMER STATES THAT THE HEATED STEERING WHEEL INTERMITTENTLY DOES NOT WORK / STATES THAT THE LIGHT DOES NOT ILLUMINATE AT ALL ANDTHE STEER ING WHEEL DOES NOT HEAT---PLEASE ADVISE (CUSTOMER SHOWED ADVISOR A VID EO OF IT HAPPENING)                     1
Name: count, dtype: int64

Column: CAUSAL_PART_NM
Missing %: 5.0
Unique values: 18
Most frequent value: WHEEL ASM-STRG *JET BLACK
Top 5 value counts:
 CAUSAL_PART_NM
WHEEL ASM-STRG *JET BLACK        45
WHEEL ASM-STRG *BLACK            12
WHEEL ASM-STRG *VERY DARK AT      7
WHEEL ASM-STRG *BACKEN BLACKK     5
MODULE ASM-STRG WHL HT CONT       5
Name: count, dtype: int64

Column: GLOBAL_LABOR_CODE_DESCRIPTION
Missing %: 0.0
Unique values: 4
Most frequent value: Steering Wheel Replacement
Top 5 value counts:
 GLOBAL_LABOR_CODE_DESCRIPTION
Steering Wheel Replacement                               78
Steering Wheel Spoke Cover Replacement                   11
Heated Steering Wheel Module Replacement                  6
Steering Wheel Horn Switch Wiring Harness Replacement     5
Name: count, dtype: int64

Column: PLATFORM
Missing %: 0.0
Unique values: 11
Most frequent value: Full-Size Trucks
Top 5 value counts:
 PLATFORM
Full-Size Trucks             52
Full-Size Utility            13
Crossover SUV                11
Global Crossover Vehicles     7
Global Gamma                  7
Name: count, dtype: int64

Column: BODY_STYLE
Missing %: 0.0
Unique values: 6
Most frequent value: Crew Cab
Top 5 value counts:
 BODY_STYLE
Crew Cab          50
4 Door Utility    37
4 Door Sedan      10
Single Cab         1
Extended Cab       1
Name: count, dtype: int64

Column: VPPC
Missing %: 0.0
Unique values: 26
Most frequent value: T1CCF
Top 5 value counts:
 VPPC
T1CCF    20
T1CGF    17
T1CGH     7
C1UL      6
T1CCH     6
Name: count, dtype: int64

Column: PLANT
Missing %: 1.0
Unique values: 11
Most frequent value: SIL
Top 5 value counts:
 PLANT
SIL    19
FTW    17
SHT    15
ARL    13
FLT    11
Name: count, dtype: int64

Column: BUILD_COUNTRY
Missing %: 0.0
Unique values: 3
Most frequent value: US
Top 5 value counts:
 BUILD_COUNTRY
US    73
MX    23
CA     4
Name: count, dtype: int64

Column: LAST_KNOWN_DLR_NAME
Missing %: 0.0
Unique values: 100
Most frequent value: AllStar Car Traders
Top 5 value counts:
 LAST_KNOWN_DLR_NAME
Silverstone Motors     1
Monarch Auto Co.       1
AllStar Car Traders    1
Ironclad Auto Sales    1
MetroStar Motors       1
Name: count, dtype: int64

Column: LAST_KNOWN_DLR_CITY
Missing %: 0.0
Unique values: 94
Most frequent value: BOLINGBROOK
Top 5 value counts:
 LAST_KNOWN_DLR_CITY
HOUSTON         2
BOLINGBROOK     2
GRAND RAPIDS    2
SMITHTOWN       2
SHERMAN OAKS    2
Name: count, dtype: int64

Column: REPAIRING_DEALER_CODE
Missing %: 0.0
Unique values: 95
Most frequent value: 11-46346/118677
Top 5 value counts:
 REPAIRING_DEALER_CODE
11-46346/118677    3
11-45870/322530    2
13-14819/243038    2
13-11298/227245    2
13-20701/295507    1
Name: count, dtype: int64

Column: DEALER_NAME
Missing %: 0.0
Unique values: 100
Most frequent value: Apex Auto Sales
Top 5 value counts:
 DEALER_NAME
Apex Auto Sales          1
BlueLine Auto Traders    1
SummitDrive Car Sales    1
GoldStar Motors          1
CityEdge Auto Sales      1
Name: count, dtype: int64

Column: REPAIR_DLR_CITY
Missing %: 0.0
Unique values: 93
Most frequent value: GRAND RAPIDS
Top 5 value counts:
 REPAIR_DLR_CITY
SIGNAL HILL     3
GRAND RAPIDS    3
BAY SHORE       2
BOLINGBROOK     2
HOUSTON         2
Name: count, dtype: int64

Column: STATE
Missing %: 2.0
Unique values: 39
Most frequent value: CA
Top 5 value counts:
 STATE
CA    9
FL    9
TX    8
OH    6
MI    5
Name: count, dtype: int64

Column: REPAIR_DLR_POSTAL_CD
Missing %: 2.0
Unique values: 92
Most frequent value: 907551909
Top 5 value counts:
 REPAIR_DLR_POSTAL_CD
907551909    3
557444215    2
770653605    2
604403522    2
117061211    2
Name: count, dtype: int64

Column: COMPLAINT_CD
Missing %: 0.0
Unique values: 7
Most frequent value: 0-0890
Top 5 value counts:
 COMPLAINT_CD
0-0890    40
0-0310    33
0-0312    12
0-0621     7
0-0313     4
Name: count, dtype: int64

Column: VEH_TEST_GRP
Missing %: 2.0
Unique values: 23
Most frequent value: T05.3386
Top 5 value counts:
 VEH_TEST_GRP
T05.3386    19
T06.2375    17
T03.6151    13
D06.6385     8
V00.0002     7
Name: count, dtype: int64

Column: COUNTRY_SALE_ISO
Missing %: 0.0
Unique values: 6
Most frequent value: US
Top 5 value counts:
 COUNTRY_SALE_ISO
US    84
CA    12
IL     1
KW     1
MX     1
Name: count, dtype: int64

Column: OPTN_FAMLY_CERTIFICATION
Missing %: 10.0
Unique values: 3
Most frequent value: FE9
Top 5 value counts:
 OPTN_FAMLY_CERTIFICATION
FE9    62
NE1    19
YF5     9
Name: count, dtype: int64

Column: OPTF_FAMLY_EMISSIOF_SYSTEM
Missing %: 5.0
Unique values: 8
Most frequent value: FTB
Top 5 value counts:
 OPTF_FAMLY_EMISSIOF_SYSTEM
FTB    62
FUC    16
FF6     5
FT7     4
FUG     3
Name: count, dtype: int64

Column: TRANSACTION_CATEGORY
Missing %: 0.0
Unique values: 2
Most frequent value: FREG
Top 5 value counts:
 TRANSACTION_CATEGORY
FREG        89
FREG_POL    11
Name: count, dtype: int64

Column: ENGINE
Missing %: 0.0
Unique values: 12
Most frequent value: L84
Top 5 value counts:
 ENGINE
L84    24
L87    17
EN0    12
LGX    11
L5P     9
Name: count, dtype: int64

Column: ENGINE_DESC
Missing %: 0.0
Unique values: 12
Most frequent value: GAS, 8 CYL, 5.3L, V8, DI, DFM, ALUM, GEN 5
Top 5 value counts:
 ENGINE_DESC
GAS, 8 CYL, 5.3L, V8, DI, DFM, ALUM, GEN 5                   24
GAS, 8 CYL, V8, 6.2L, DI, DFM, ALUM, GEN 5                   17
NONE                                                         12
GAS, 6 CYL, 3.6L, V6, DI, DOHC, VVT, ALUM, GEN 2             11
DIESEL, 8 CYL, 6.6L, DI, V8, TURBO, DURAMAX, GEN 5 VAR. 1     9
Name: count, dtype: int64

Column: TRANSMISSION
Missing %: 0.0
Unique values: 19
Most frequent value: MHS
Top 5 value counts:
 TRANSMISSION
MHS    28
M3W    12
MQC    11
MGM     9
MQB     7
Name: count, dtype: int64

Column: TRANSMISSION_DESC
Missing %: 0.0
Unique values: 20
Most frequent value: BYT 10 SPD, 10L80, GRX, GEN 1, ATSS, ETRS, VAR 1
Top 5 value counts:
 TRANSMISSION_DESC
BYT 10 SPD, 10L80, GRX, GEN 1, ATSS, ETRS, VAR 1    28
TRANSMISSION BYT 9 SPD, 9T65, ETRS GEN 1            12
BYT 10 SPD, 10L80, ATSS, ETRS, CPA, GEN 2           10
BYT 10 SPD, 10R1000, GRX, GEN 1, VAR 1               9
BYT 10 SPD, 10L80, ATSS, CPA, GEN 2                  7
Name: count, dtype: int64

Column: ENGINE_SOURCE_PLANT
Missing %: 12.0
Unique values: 9
Most frequent value: 830107152
Top 5 value counts:
 ENGINE_SOURCE_PLANT
830107152    15
249196973    14
2127157      12
70628511     11
37749264     11
Name: count, dtype: int64

Column: ENGINE_TRACE_NBR
Missing %: 12.0
Unique values: 88
Most frequent value: V2210281MFTX0488
Top 5 value counts:
 ENGINE_TRACE_NBR
V2210281MFTX0488    1
V2210291MFTX0188    1
K2220892JW4X1979    1
210900289           1
N2200440CLWX0224    1
Name: count, dtype: int64

Column: TRANSMISSION_TRACE_NBR
Missing %: 12.0
Unique values: 88
Most frequent value: 21210129IKBP0429
Top 5 value counts:
 TRANSMISSION_TRACE_NBR
S2210121CNJX0941    1
R2210881CNJX0287    1
S2220782CKJX0921    1
22221892QKBY1909    1
C2200240NELX0047    1
Name: count, dtype: int64

Column: MEDIA_FLAG
Missing %: 0.0
Unique values: 2
Most frequent value: N
Top 5 value counts:
 MEDIA_FLAG
N    62
Y    38
Name: count, dtype: int64

Column: VIN_MODL_DESGTR
Missing %: 0.0
Unique values: 41
Most frequent value: CF10543
Top 5 value counts:
 VIN_MODL_DESGTR
CF10543    15
TF10543    13
TF20743     6
6MB26       5
1FG48       4
Name: count, dtype: int64

Column: LINE_SERIES
Missing %: 1.0
Unique values: 22
Most frequent value: 1500
Top 5 value counts:
 LINE_SERIES
1500              52
2500              11
Sport              5
Premier            5
Premium Luxury     3
Name: count, dtype: int64

=== Numerical Column Insights ===

Column: TRANSACTION_ID
Missing %: 0.0
count      100.000000
mean     13036.900000
std         12.028166
min      13021.000000
25%      13027.750000
50%      13036.000000
75%      13041.250000
max      13081.000000
Name: TRANSACTION_ID, dtype: float64

Column: DEALER_REGION
Missing %: 0.0
count    100.00000
mean       1.09000
std        0.51434
min        1.00000
25%        1.00000
50%        1.00000
75%        1.00000
max        4.00000
Name: DEALER_REGION, dtype: float64

Column: REPAIR_AGE
Missing %: 0.0
count    100.000000
mean      14.940000
std       12.367945
min        0.000000
25%        5.000000
50%       12.000000
75%       21.000000
max       50.000000
Name: REPAIR_AGE, dtype: float64

Column: KM
Missing %: 0.0
count       100.000000
mean      24914.230000
std       20747.078206
min           3.000000
25%        8883.250000
50%       21962.000000
75%       35493.250000
max      107905.000000
Name: KM, dtype: float64

Column: COMPLAINT_CD_CSI
Missing %: 0.0
count    100.0
mean       0.0
std        0.0
min        0.0
25%        0.0
50%        0.0
75%        0.0
max        0.0
Name: COMPLAINT_CD_CSI, dtype: float64

Column: ORD_SELLING_SRC_CD
Missing %: 0.0
count    100.000000
mean      24.590000
std       17.822976
min       11.000000
25%       13.000000
50%       13.000000
75%       48.000000
max       72.000000
Name: ORD_SELLING_SRC_CD, dtype: float64

Column: GLOBAL_LABOR_CODE
Missing %: 0.0
count     100.000000
mean      251.900000
std       546.451722
min        20.000000
25%       130.000000
50%       130.000000
75%       130.000000
max      2400.000000
Name: GLOBAL_LABOR_CODE, dtype: float64

Column: CAMPAIGN_NBR
Missing %: 100.0
count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: CAMPAIGN_NBR, dtype: float64

Column: REPORTING_COST
Missing %: 0.0
count     100.000000
mean      531.193200
std       411.161608
min        27.690000
25%       305.432500
50%       433.970000
75%       554.062500
max      2457.450000
Name: REPORTING_COST, dtype: float64

Column: TOTALCOST
Missing %: 6.0
count      94.000000
mean      561.162128
std       452.796836
min        27.690000
25%       320.105000
50%       457.225000
75%       606.905000
max      3205.450000
Name: TOTALCOST, dtype: float64

Column: LBRCOST
Missing %: 0.0
count     100.000000
mean      106.344900
std       113.223074
min        20.000000
25%        61.855000
50%        78.560000
75%       108.055000
max      1012.670000
Name: LBRCOST, dtype: float64

Column: TRANSMISSION_SOURCE_PLANT
Missing %: 12.0
count    8.800000e+01
mean     1.676383e+08
std      3.237538e+08
min      2.878270e+05
25%      2.878270e+05
50%      8.042172e+06
75%      1.774929e+07
max      8.282984e+08
Name: TRANSMISSION_SOURCE_PLANT, dtype: float64

Column: SRC_TXN_ID
Missing %: 0.0
count    1.000000e+02
mean     2.815767e+09
std      5.790727e+06
min      2.808842e+09
25%      2.809436e+09
50%      2.820097e+09
75%      2.820880e+09
max      2.823000e+09
Name: SRC_TXN_ID, dtype: float64

Column: SRC_VER_NBR
Missing %: 0.0
count    100.000000
mean       5.720000
std        4.040402
min        2.000000
25%        4.000000
50%        4.000000
75%        6.000000
max       26.000000
Name: SRC_VER_NBR, dtype: float64

Column: TRANSACTION_CNTR
Missing %: 0.0
count    100.0
mean       1.0
std        0.0
min        1.0
25%        1.0
50%        1.0
75%        1.0
max        1.0
Name: TRANSACTION_CNTR, dtype: float64

Column: LAST_KNOWN_DELVRY_TYPE_CD
Missing %: 2.0
count    98.000000
mean     14.132653
std       6.694570
min      10.000000
25%      10.000000
50%      10.000000
75%      16.000000
max      37.000000
Name: LAST_KNOWN_DELVRY_TYPE_CD, dtype: float64

Column: NON_CAUSAL_PART_QTY
Missing %: 0.0
count    100.000000
mean       0.070000
std        0.256432
min        0.000000
25%        0.000000
50%        0.000000
75%        0.000000
max        1.000000
Name: NON_CAUSAL_PART_QTY, dtype: float64

Column: SALES_REGION_CODE
Missing %: 0.0
count    100.00000
mean       1.09000
std        0.51434
min        1.00000
25%        1.00000
50%        1.00000
75%        1.00000
max        4.00000
Name: SALES_REGION_CODE, dtype: float64

=== Datetime Column Insights ===

Column: REPAIR_DATE
Missing %: 0.0
Min date: 2024-01-02 00:00:00
Max date: 2024-02-07 00:00:00
Unique dates: 29

C:\Users\Admin\AppData\Local\Temp\ipykernel_8004\1479080738.py:18: UserWarning: Unable to sort modes: '<' not supported between instances of 'int' and 'str'
  print("Most frequent value:", data[col].mode()[0])

In [16]:


print("=== Potential Data Quality Issues ===")



# 3. Constant columns (only 1 unique value â†’ no useful info)
constant_cols = [col for col in data.columns if data[col].nunique() <= 1]
print("\n Constant Columns:", constant_cols)

# 4. High cardinality categorical columns
cat_cols = data.select_dtypes(include=['object', 'category']).columns
for col in cat_cols:
    unique_ratio = data[col].nunique() / len(data)
    if unique_ratio > 0.9:  # >90% unique values = suspicious for categorical
        print(f"\n High cardinality column (possible ID): {col} ({data[col].nunique()} unique values)")

# 5. Outliers in numeric columns (using IQR rule)
num_cols = data.select_dtypes(include=['number']).columns
for col in num_cols:
    Q1 = data[col].quantile(0.25)
    Q3 = data[col].quantile(0.75)
    IQR = Q3 - Q1
    outliers = data[(data[col] < (Q1 - 1.5 * IQR)) | (data[col] > (Q3 + 1.5 * IQR))]
    if not outliers.empty:
        print(f"\n Possible outliers detected in column: {col} ({len(outliers)} rows)")

# 6. Datetime columns with strange ranges
date_cols = data.select_dtypes(include=['datetime64[ns]']).columns
for col in date_cols:
    if data[col].notnull().sum() > 0:
        min_date, max_date = data[col].min(), data[col].max()
        print(f"\nðŸ”¹ Datetime column {col}: min={min_date}, max={max_date}")

=== Potential Data Quality Issues ===

 Constant Columns: ['COMPLAINT_CD_CSI', 'CAMPAIGN_NBR', 'TRANSACTION_CNTR']

 High cardinality column (possible ID): VIN (98 unique values)

 High cardinality column (possible ID): CORRECTION_VERBATIM (93 unique values)

 High cardinality column (possible ID): CUSTOMER_VERBATIM (100 unique values)

 High cardinality column (possible ID): LAST_KNOWN_DLR_NAME (100 unique values)

 High cardinality column (possible ID): LAST_KNOWN_DLR_CITY (94 unique values)

 High cardinality column (possible ID): REPAIRING_DEALER_CODE (95 unique values)

 High cardinality column (possible ID): DEALER_NAME (100 unique values)

 High cardinality column (possible ID): REPAIR_DLR_CITY (93 unique values)

 High cardinality column (possible ID): REPAIR_DLR_POSTAL_CD (92 unique values)

 Possible outliers detected in column: TRANSACTION_ID (5 rows)

 Possible outliers detected in column: DEALER_REGION (3 rows)

 Possible outliers detected in column: REPAIR_AGE (4 rows)

 Possible outliers detected in column: KM (2 rows)

 Possible outliers detected in column: GLOBAL_LABOR_CODE (22 rows)

 Possible outliers detected in column: REPORTING_COST (13 rows)

 Possible outliers detected in column: TOTALCOST (11 rows)

 Possible outliers detected in column: LBRCOST (10 rows)

 Possible outliers detected in column: TRANSMISSION_SOURCE_PLANT (18 rows)

 Possible outliers detected in column: SRC_VER_NBR (10 rows)

 Possible outliers detected in column: LAST_KNOWN_DELVRY_TYPE_CD (6 rows)

 Possible outliers detected in column: NON_CAUSAL_PART_QTY (7 rows)

 Possible outliers detected in column: SALES_REGION_CODE (3 rows)

ðŸ”¹ Datetime column REPAIR_DATE: min=2024-01-02 00:00:00, max=2024-02-07 00:00:00